/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner sc = new Scanner(System.in);

        int option = 0;
        UserBookingService userBookingService;

        try{
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("There is something wrong!!");
            return;
        }

        while (option != 7) {
            System.out.println("Choose options");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book A Seat");
            System.out.println("6. Cancel My Booking");
            System.out.println("7. Exit The App");
            option = sc.nextInt();
        
            switch (option) {
                case 1 -> {
                    System.out.print("Enter name to signup: ");
                    String name = sc.next();
                    System.out.print("Enter password: ");
                    String password = sc.next();
                    User newUser = new User(name, password, UserServiceUtil.hashPassword(password),new ArrayList<>(), UUID.randomUUID().toString());
                    if (userBookingService.signUp(newUser)) {
                        System.out.println("Sign up successful!");
                    } else {
                        System.out.println("Sign up failed. Try again.");
                    }
                }
                case 2 -> {
                    System.out.print("Enter name: ");
                    String name = sc.next();
                    System.out.print("Enter password: ");
                    String password = sc.next();
                    User newUser = new User(name, password, UserServiceUtil.hashPassword(password),new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(newUser);
                    } catch (IOException e) {
                        return;
                    }
                    break;
                }
                case 3 -> {
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                }
                case 4 -> {
                    System.out.println("Search Trains functionality not implemented yet.");
                }
                case 5 -> {
                    // Placeholder for booking seat functionality
                    System.out.println("Book a Seat functionality not implemented yet.");
                }
                case 6 -> {
                    System.out.print("Enter Ticket ID to cancel: ");
                    String ticketId = sc.next();
                    try {
                        if (userBookingService.cancelBooking(ticketId)) {
                            System.out.println("Ticket cancelled successfully!");
                        } else {
                            System.out.println("Failed to cancel ticket. Check your Ticket ID.");
                        }
                    } catch (IOException e) {
                        System.out.println("An error occurred while cancelling the ticket.");
                    }
                }
                case 7 -> System.out.println("Exiting the application. Goodbye!");
                default -> System.out.println("Invalid option. Please choose a valid menu option.");
            }
        }

    }
}
